console.log(/ca[rt]/.test("car"))
console.log(/pr?op/.test("pop"))
console.log(/ferr(et|y|ari)/.test("ferrari"))
console.log(/ious\b/.test("I am impervious"))
console.log(/\s[.,:;]/.test(" ;"))
console.log(/\w{7,}/.test("mediocre"))
console.log(/\b[^e]+\b/i.test("grift"))